id: AD6468D30
title: CII_Verses 61-75
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:39:56.924010
  last_modified_at: 2022-03-01 23:39:56.924016
