id: AD6468D30
title: CII_Verses 41-60
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:39:56.919133
  last_modified_at: 2022-03-01 23:39:56.919190
