id: AD6468D30
title: CIX_Verses 21-27
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:39:56.937419
  last_modified_at: 2022-03-01 23:39:56.937424
