id: AD6468D30
title: CXI_Verses 1-15
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:39:56.985333
  last_modified_at: 2022-03-01 23:39:56.985340
