id: AD6468D30
title: CXI_Verses 16-33
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:39:56.989429
  last_modified_at: 2022-03-01 23:39:56.989436
