id: AD6468D30
title: Colophon
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:39:57.000804
  last_modified_at: 2022-03-01 23:39:57.000811
