id: AD6468D30
title: CVI_Verses 21-40
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:39:56.962429
  last_modified_at: 2022-03-01 23:39:56.962436
