id: AD6468D30
title: CVII_Verses 1-22
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:39:56.954345
  last_modified_at: 2022-03-01 23:39:56.954352
