id: AD6468D30
title: CII_Verses 21-40
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:39:56.913359
  last_modified_at: 2022-03-01 23:39:56.913365
