id: AD6468D30
title: CIX_Verses 1-20
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:39:56.933104
  last_modified_at: 2022-03-01 23:39:56.933137
