id: AD6468D30
title: CVIII_Verses 21-34
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:39:56.949002
  last_modified_at: 2022-03-01 23:39:56.949027
