id: AD6468D30
title: CVI_Verses 1-20
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:39:56.958028
  last_modified_at: 2022-03-01 23:39:56.958034
